Complete dvc setup with remote and metrics
Release-Engineering-4/RE-project-team-4 pull request #4
Opened 2024-05-05 14:44 UTC by smrutik25

2024-05-05 22:15 UTC, mln9d4 requested changes
Code does not work due to file path directories being written with "\\" in the src files. Should be changed to "/" and it should work in both Windows and Linux. 

After changing it locally running dvc repro works, and it trains the model. I will check if the other stages work tomorrow.

Futher more to fix the pipeline please fix the following file "REMLA_PROJECT/src/visualization/evaluation.py".

1. Re-oder import so JSON is above Seaborn
2. Breakline of the sklearn.metrics import so it doesn't become too long I.E.
`from sklearn.metrics import (classification_report,
                            confusion_matrix,
                            accuracy_score,
                            roc_auc_score,
                            f1_score)`
3. Add encoding to with open() statements : `with open(file, read/write, encoding='utf-8)`

2024-05-06 07:44 UTC, mln9d4 requested changes

2024-05-06 07:44 UTC, mln9d4 commented on REMLA_PROJECT/src/visualization/evaluation.py
> -from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
`import json`
should be above `import seaborn as sns`

2024-05-06 07:44 UTC, mln9d4 commented on REMLA_PROJECT/src/visualization/evaluation.py
> +from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, roc_auc_score, f1_score
```
from sklearn.metrics import (classification_report,
                            confusion_matrix,
                            accuracy_score,
                            roc_auc_score,
                            f1_score)
```

2024-05-06 07:44 UTC, mln9d4 commented on REMLA_PROJECT/src/visualization/evaluation.py
> +    with open("REMLA_PROJECT\\reports\\metrics.json", "w") as json_file:
change it to `with open("REMLA_PROJECT/reports/metrics.json", "w", encoding="utf-8") as json_file:`

2024-05-06 09:51 UTC, smrutik25 commented
Made the changes and it ran successfully

2024-05-06 10:01 UTC, mln9d4 approved these changes

2024-05-06 10:02 UTC, merged